api_platform:
    title: IKEA
    description: API Warehouse Management System
    version: 0.0.1
    show_webby: false
    exception_to_status:
        App\Exception\OutOfStockException: 400
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
